FROM ubuntu:17.10
LABEL maintainer="Jared Harrington-Gibbs"
LABEL description="A docker image that runs wireshark"

RUN apt-get update && \ 
    DEBIAN_FRONTEND=noninteractive apt-get install -y wireshark openssh-server tightvncserver && \
    apt-get autoremove -y && \
    apt-get autoclean -y && \
    rm -rf /var/lib/apt/lists/* 

CMD ["wireshark"]
